### PR TITLE
fix: fix SDE connection filename prefixes

### PR DESCRIPTION
**Pull request by stdavis**
Looks like they were swapped. Not sure how this is working for you before this change?

### CODE REVIEW

**Comment by ZachBeck** [comment]
it should be fixed now

**Comment by stdavis** [comment]
What did you fix? I thought that the fix was the changes in this PR.

**Comment by ZachBeck** [comment]
I guess I don't know what you're talking about

**Comment by stdavis** [comment]
Looks like @ZachBeck already had this fixed in 0bbff9aca3833754bf1f67ad91978a32846c0529.

**Pull request closed without merging**
